name: Hello World
author: Hira Jabeen
description: "Greet someone and record the time"
inputs:
  who_to_greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  time:
    description: The time of the greeting
runs:
  using: "node20"
  main: "index.js"
  pre: "setup.js"
  pre-if: "runner.os == 'Linux'"
  post: "cleanup.js"
  post-if: "runner.os == 'Linux'"
