name: Caching and Artifacts
on: [workflow_dispatch]
jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-
      - name: Display Cache Output
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Ensure Coverage Directory
        run: mkdir -p coverage
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: code-coverage
          path: coverage
          retention-days: 10
      - name: Download Code Coverage
        uses: actions/download-artifact@v4
        with:
          name: code-coverage
          path: code-coverage-report
      - name: List All Files
        run: ls -a
      - name: List Files in Code Coverage Directory
        run: ls -a
        working-directory: code-coverage-report
      - name: Use Axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
              .then(res => {
                console.log(res.data);
              })
              .catch(error => {
                console.error('Error fetching joke:', error);
                process.exit(1); // Exit with code 1 if there's an error
              });
