name: Matrix
on: [push]

#------- ORIGINAL --------#
# X {os: ubuntu-latest, node-version: 14, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 15, is-ubuntu: true, experimental: false}
# {os: ubuntu-latest, node-version: 16, is-ubuntu: true, experimental: true}
# {os: windows-latest, node-version: 14, experimental: false}
# {os: windows-latest, node-version: 15, experimental: false}
# {os: windows-latest, node-version: 16, experimental: false}
# {os: macos-latest, node-version: 15}
# {os: ubuntu-latest, node-version: 17 }
jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 15, 16, 17]
        include:
          - os: ubuntu-latest
            node-version: 16
            is-ubuntu: true
            experimental: true
          - os: ubuntu-latest
            node-version: 17
            is-ubuntu: true
            experimental: false
        exclude:
          - os: ubuntu-latest
            node-version: 14
          - os: macos-latest
            node-version: 14
          - os: macos-latest
            node-version: 15
          - os: macos-latest
            node-version: 17
          - os: windows-latest
            node-version: 15
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.experimental == true
        run: exit 1
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - run: node -v
