name: Matrix
on: [push]

jobs:
  node-matrix:
    continue-on-error: false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14, 15, 16, 17]
        include:
          - os: ubuntu-latest
            node-version: 16
            is-ubuntu: true
            experimental: true
          - os: ubuntu-latest
            node-version: 17
            is-ubuntu: true
            experimental: false
        exclude:
          - os: ubuntu-latest
            node-version: 14
          - os: macos-latest
            node-version: 14
          - os: macos-latest
            node-version: 15
          - os: macos-latest
            node-version: 17
          - os: windows-latest
            node-version: 15
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - run: node -v
      - run: echo '${{ toJson(matrix) }}'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - run: node -v
