name: Variables and Secrets
on: [push]

jobs:
  decrypt-file:
    runs-on: ${{ vars.JOB_RUNNERS }}
    steps:
      - uses: actions/checkout@v3
      - name: Decrypt File
        env: 
          PASSPHRASE: ${{secrets.PASSPHRASE}}
        run: |
            mkdir $HOME/secrets
            gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output $HOME/secrets/secret.json data.json.gpg
      - name: View Encrypted File Content
        run : cat $HOME/secrets/secret.json

  log-vars:
    runs-on: ${{ vars.JOB_RUNNERS }}
    environment: 'production'
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR}}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
      ORG_LEVEL_VAR: ${{ vars.ORG_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I ran"
      - name: Log Vars
        run: |
          echo '${{ vars.JOB_RUNNERS }}'
          echo "ORG_LEVEL_VAR: $ORG_LEVEL_VAR"
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"