name: Working Directory & Shells
on: [push]
jobs:
  display-with-info:
    runs-on: ubuntu-latest  
    steps:
      - name: Display Working Directory & List Files
        run: |
         pwd
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         
  display-with-info-windows:
     runs-on: windows-latest  
     steps:
       - name: Display Working Directory & List Files with windows
         run: |
                 pwd
                 ls -a
                 echo $GITHUB_SHA
                 echo $GITHUB_REPOSITORY
                 echo $GITHUB_WORKSPACE